version: '3'
services:
  nginx:
    container_name: app-formation-web-nginx
    depends_on:
      - engine
    image: nginx:1.16
    ports:
      - "80:80"
    volumes:
      - ./symfony/public:/home/docker/public:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default

  engine:
    container_name: app-formation-web-engine
    image: public.ecr.aws/a7b6b1u3/formation-php-hexaom:8.1.8-alpine
#    build: ./docker/dev/engine/
    depends_on:
      - db
    volumes:
      - ./symfony:/home/docker:cached
      - ./docker/engine/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    working_dir: /home/docker
    networks:
      - default

  db:
    container_name: app-formation-web-db
    image: mariadb:10.4
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - TZ=UTC
    networks:
      - default
    volumes:
      - ./tmp/mariadb-10.4:/var/lib/mysql:rw
      - ./docker/db/init:/docker-entrypoint-initdb.d

networks:
  default: {}
