vich_uploader:
  db_driver: orm
  storage: flysystem

  mappings:
    uploadedFiles:
      uri_prefix: /images
      upload_destination: default.storage
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: true
      delete_on_remove: true
